import Link from 'next/link'
import ProductCard from './components/ProductCard'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import Image from 'next/image'
import coffeeOne from '@/public/images/coffee-one.jpg'
import { Metadata } from 'next'

export default async function Home() {
  const session = await getServerSession(authOptions)

  return (
    <main className="relative h-screen">
      {/* <Image
        src="https://bit.ly/react-cover"
        fill
        alt="Coffee"
        className="object-cover "
        sizes="(max-width: 480px) 100vw, (max-width: 768px) 50vw, 33vw"
        quality={100}
        priority={true}
      /> */}
      <h1>Hello World</h1>
    </main>
  )
}

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   openGraph: {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//     images: 'https://bit.ly/3yqZLZU',
//   },
// }

export async function generateMetadata(): Promise<Metadata> {
  const data = await fetch('https://fakestoreapi.com/products/1')

  return {
    title: 'Testing title',
    description: 'Testing description...',
    openGraph: {
      title: 'Testing social title',
      description: 'Testing social description...',
      images: 'https://bit.ly/3yqZLZU',
    },
  }
}
