'use client'
import React from 'react'

export default function Home() {
  return (
    <main className="relative h-screen">
      {/* <Image
        src="https://bit.ly/react-cover"
        fill
        alt="Coffee"
        className="object-cover "
        sizes="(max-width: 480px) 100vw, (max-width: 768px) 50vw, 33vw"
        quality={100}
        priority={true}
      /> */}
      <h1>Hello World</h1>
      <button
        onClick={async () => {
          const _ = (await import('lodash')).default
          const users = [
            {
              name: 'c',
            },
            {
              name: 'b',
            },
            {
              name: 'a',
            },
          ]

          const sortedUsers = _.orderBy(users, ['name'])
          console.log(sortedUsers)
        }}
      >
        Show
      </button>
    </main>
  )
}

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   openGraph: {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//     images: 'https://bit.ly/3yqZLZU',
//   },
// }

// export async function generateMetadata(): Promise<Metadata> {
//   const data = await fetch('https://fakestoreapi.com/products/1')

//   return {
//     title: 'Testing title',
//     description: 'Testing description...',
//     openGraph: {
//       title: 'Testing social title',
//       description: 'Testing social description...',
//       images: 'https://bit.ly/3yqZLZU',
//     },
//   }
// }
